server:
  port: 8888

app:
  api-prefix: /api
  strip-prefix: 1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix= ${app.strip-prefix}

        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix= ${app.strip-prefix}

        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix= ${app.strip-prefix}